name: Test de workflow

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  my-new-job:
    runs-on: ubuntu-latest

    steps:
      - name: Messages utiles
        run: |
          echo "Récupération du code source"
          echo "Vérification terminée"
