name: Test de workflow

on: 
  workflow_dispatch:
  jobs:
  
  my-new-job:
    runs-on: ubuntu-latest

    steps:
      - name: Message utile A
        run:
          echo "Récupération du code source"
      - name: Message utile B
        run:
          echo "Vérification terminée"
